github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://apps.serp.co/serp-video-downloader",
"https://serp.co/products/serp-video-downloader/reviews/",
"https://whop.com/serp-downloaders/serp-video-downloader/"
]
